#!/bin/bash
set -e

## Execute the command below from the root folder of the feature to run this test in isolation:
# devcontainer features test --features matlab --skip-autogenerated --filter install_release_on_ubuntu24.04

# Optional: Import test library bundled with the devcontainer CLI
source dev-container-features-test-lib

check "r2025a is installed" bash -c "cat /opt/matlab/R2025a/VersionInfo.xml | grep '<release>R2025a</release>'"

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults